"""add lead status

Revision ID: 79e37a0b8493
Revises: 4f86af85c2c0
Create Date: 2026-07-19 17:32:07.223156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e37a0b8493'
down_revision: Union[str, None] = '4f86af85c2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leads', sa.Column('status', sa.String(), nullable=True))
    op.execute("UPDATE leads SET status = 'new' WHERE status IS NULL")
    op.alter_column('leads', 'status', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leads', 'status')
    # ### end Alembic commands ###
